name: Deploy Modal Server

on:
  push:
    branches: [ main, master ]
    paths:
      - 'modal_server.py'
      - 'requirements.txt'
      - '.github/workflows/deploy-modal.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Authenticate with Modal
      run: |
        modal token set --token-id "$MODAL_TOKEN_ID" --token-secret "$MODAL_TOKEN_SECRET"
      env:
        MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
        MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}        

    - name: Deploy to Modal
      run: |
        modal deploy modal_server.py
        
    - name: Verify deployment
      run: |
        modal app list | grep live2d-action-server || echo "App not found in list"
